apps/df_music/urls.py
from django.conf.urls import url

from . import views

app_name = 'df_goods'

urlpatterns = [
    url('^$', views.index, name="index"),
    url('^list(\d+)_(\d+)_(\d+)/$', views.song_list, name="song_list"),
    url('^(\d+)/$', views.detail, name="detail"),
    url(r'^search/', views.ordinary_search, name="ordinary_search"),  # 全文检索
]

musicrec/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include
from django.views.static import serve
from .settings import MEDIA_ROOT
urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^',include('df_music.urls',namespace='df_goods')),
    url(r'^user/',include('df_user.urls',namespace='df_user')),
    url(r'^tinymce/',include('tinymce.urls')),
    url(r'^media/(?P<path>.*)$', serve, {"document_root":MEDIA_ROOT}),


]

apps/df_music/models.py
from django.db import models
from datetime import datetime
from tinymce.models import HTMLField
# Create your models here.
#音乐分类
class TypeInfo(models.Model):
    isDelete=models.BooleanField(default=False)
    title=models.CharField(max_length=20,verbose_name="分类")

    class Meta:
        verbose_name="音乐类型"
        verbose_name_plural=verbose_name


    def __str__(self):
        return self.title

#具体音乐信息
class MusicInfo(models.Model):
    isDelete=models.BooleanField(default=False)
    mtitle=models.CharField(max_length=40,verbose_name="音乐名称")
    mpic=models.ImageField(verbose_name="音乐图片",upload_to="df_music/image/%Y/%m",null=True,blank=True)
    mclick=models.IntegerField(verbose_name="点击量",default=0,null=False)
    mcontext=HTMLField(max_length=200,verbose_name="详情")
    mtype=models.ForeignKey(TypeInfo,on_delete=models.CASCADE,verbose_name="分类")

    class Meta:
        verbose_name="歌曲"
        verbose_name_plural=verbose_name
    def __str__(self):
        return self.mtitle

apps/df_music/views.py
from django.shortcuts import render
from django.core.paginator import Paginator
from datetime import datetime
from df_user.models  import MusicBrowser
from django.db.models import Q
import random
import pandas as pd
from sqlalchemy import create_engine
engine = create_engine('mysql+pymysql://root:19981002@localhost:3306/musicre?charset=utf8')
df1 = pd.read_sql_table('song_recm', engine)
# Create your views here.
from .models import MusicInfo,TypeInfo
from .Recommenders import *
def index(request):

    typelist=TypeInfo.objects.all()
    type0=typelist[0].musicinfo_set.order_by('-id')[0:4]
    type01=typelist[0].musicinfo_set.order_by('-mclick')[0:4]
    type1=typelist[1].musicinfo_set.order_by('-id')[0:4]
    type11=typelist[1].musicinfo_set.order_by('-mclick')[0:4]
    type2=typelist[2].musicinfo_set.order_by('-id')[0:4]
    type21=typelist[2].musicinfo_set.order_by('-mclick')[0:4]
    type3=typelist[3].musicinfo_set.order_by('-id')[0:4]
    type31=typelist[3].musicinfo_set.order_by('-mclick')[0:4]
    type4=typelist[4].musicinfo_set.order_by('-id')[0:4]
    type41=typelist[4].musicinfo_set.order_by('-mclick')[0:4]
    type5=typelist[5].musicinfo_set.order_by('-id')[0:4]
    type51=typelist[5].musicinfo_set.order_by('-mclick')[0:4]
    if request.session.get('user_id') is not None:
        typelist = TypeInfo.objects.all()
        type0 = []
        type1 = []
        type2 = []
        type3 = []
        type4 = []
        type5 = []
        type01 = typelist[0].musicinfo_set.order_by('-mclick')[0:4]
        type11 = typelist[1].musicinfo_set.order_by('-mclick')[0:4]
        type21 = typelist[2].musicinfo_set.order_by('-mclick')[0:4]
        type31 = typelist[3].musicinfo_set.order_by('-mclick')[0:4]
        type41 = typelist[4].musicinfo_set.order_by('-mclick')[0:4]
        type51 = typelist[5].musicinfo_set.order_by('-mclick')[0:4]

        n1, n2, n3, n4, n5, n6 = recommender_list()
        for i in n1:
            type0.append(MusicInfo.objects.get(id=i))
        for i in n2:
            type1.append(MusicInfo.objects.get(id=i))
        for i in n3:
            type2.append(MusicInfo.objects.get(id=i))
        for i in n4:
            type3.append(MusicInfo.objects.get(id=i))
        for i in n5:
            type4.append(MusicInfo.objects.get(id=i))
        for i in n6:
            type5.append(MusicInfo.objects.get(id=i))

        context = {
            'title': "首页",
            'type0': type0, 'type01': type01,
            'type1': type1, 'type11': type11,
            'type2': type2, 'type21': type21,
            'type3': type3, 'type31': type31,
            'type4': type4, 'type41': type41,
            'type5': type5, 'type51': type51,

        }
        return render(request, 'df_music/index.html', context)

    context = {
        'title': "首页",
        'type0': type0, 'type01': type01,
        'type1': type1, 'type11': type11,
        'type2': type2, 'type21': type21,
        'type3': type3, 'type31': type31,
        'type4': type4, 'type41': type41,
        'type5': type5, 'type51': type51,

        }
    return render(request, 'df_music/index.html', context)








def song_list(request,tid,pindex,sort):
    typeinfo=TypeInfo.objects.get(pk=int(tid))
    news=typeinfo.musicinfo_set.order_by('-id')[0:2]
    songs_list=[]

    if sort=='1':
        songs_list=MusicInfo.objects.filter(mtype=int(tid)).order_by('-mclick')[0:100]
    if sort=="2":
        songs_list=MusicInfo.objects.filter(mtype=int(tid)).order_by('-id')[0:100]

    paginator=Paginator(songs_list,10)
    page=paginator.page(int(pindex))
    context={
        'title':'歌曲列表',
        'page':page,
        'paginator':paginator,
        'typeinfo':typeinfo,
        'sort':sort,
        'news':news,

    }
    return render(request,'df_music/list.html',context)
def detail(request,mid):
    music_id=mid
    music_tit=MusicInfo.objects.get(pk=int(music_id)).mtitle
    r1 = df1.loc[df1['song_title'] == music_tit, ['song_1', 'song_2', 'song_3']]
    r2=r1.to_numpy()[0]
    song_rec=[]
    for t in r2:
        song=MusicInfo.objects.get(mtitle=t)
        song_rec.append(song)
    songs=MusicInfo.objects.get(pk=int(music_id))
    songs.mclick=songs.mclick+1
    songs.save()

    news=songs.mtype.musicinfo_set.order_by('-mclick')[0:4]

    context={
        'title':songs.mtype.title,
        'songs':songs,
        'news':news,
        'id':music_id,
        'song_rec':song_rec,
    }
    response=render(request,'df_music/detail.html',context)




    user_id=request.session["user_id"]
    if user_id is None:
        return response
    try:
        browsed_music=MusicBrowser.objects.get(user_id=int(user_id),music_id=int(music_id))
    except Exception:
        browsed_music=None
    if browsed_music:
        browsed_music.browser_time=datetime.now()
        browsed_music.save()
    else:
        MusicBrowser.objects.create(user_id=int(user_id),music_id=int(music_id))
        browsed_music=MusicBrowser.objects.filter(user_id=int(user_id))
        browsed_music_count=browsed_music.count()
        if browsed_music_count>5:
            ordered_music=browsed_music.order_by("-brower_time")
            for _ in ordered_music[5:]:
                _.delete()
    return response


def ordinary_search(request):
    search_keywords=request.GET.get('q','')
    pindex=request.GET.get('pindex',1)
    search_status=1


    music_list=MusicInfo.objects.filter(
        Q(mtitle__icontains=search_keywords)|Q(mcontext__icontains=search_keywords)
    ).order_by("mclick")
    if music_list.count()==0:
        search_status=0
        music_list=MusicInfo.objects.all().order_by("mclick")[:4]

    pageinator=Paginator(music_list,4)
    page=pageinator.page(int(pindex))


    context={
        'title':'搜索列表',
        'search_status':search_status,
        'page':page,
        'paginator':pageinator,
    }
    return render(request,'df_music/ordinary_search.html',context)


def recommender_list():
    item_similarity_recommender_py()
    popularity_recommender_py()
    SVD()
    user_popularity()


    n=random.sample(range(0,500),24)
    return split_list_n_list(n,6)



def split_list_n_list(origin_list, n):
    if len(origin_list) % n == 0:
        cnt = len(origin_list) // n
    else:
        cnt = len(origin_list) // n + 1

    for i in range(0, n):
        yield origin_list[i * cnt:(i + 1) * cnt]

templates/df_music/base.html
{% extends 'base.html' %}

{% block center_body %}

    <div class="navbar_con">
		<div class="navbar clearfix">
			<div class="subnav_con fl">
				<h1>全部音乐分类</h1>
				<span></span>
				<ul class="subnav">
					<li><a href="/list1_1_1/" class="fruit">摇滚</a></li>
					<li><a href="/list2_1_1/" class="seafood">古典</a></li>
					<li><a href="/list3_1_1/" class="meet">轻音乐</a></li>
					<li><a href="/list4_1_1/" class="egg">热歌</a></li>
					<li><a href="/list5_1_1/" class="vegetables">DJ</a></li>
					<li><a href="/list6_1_1/" class="ice">经典老歌</a></li>
				</ul>
			</div>
			<ul class="navlist fl">
				<li><a href="{% url "df_goods:index" %}">首页</a></li>

			</ul>
		</div>
	</div>

	<div class="breadcrumb">
		全部分类 > {{ title }}
		{% if id|default:' ' != ' ' %}
        > 歌曲详情
		{% endif %}
	</div>

{% block center_content %}

{% endblock center_content %}

{% endblock center_body %}

templates/df_music/detail.html
{% extends 'df_music/base.html' %}



{% block center_content %}
	<div class="goods_detail_con clearfix">
		<div class="goods_detail_pic fl"><img src="{{ MEDIA_URL }}{{ songs.mpic }}" width="300px" height="350px"></div>

		<div class="goods_detail_list fr" >
			<h3 class="blogk" style="margin-left: 300px">{{ songs.mtitle }}</h3>


		</div>
	</div>

	<div class="main_wrap clearfix">
		<div class="l_wrap fl clearfix">
			<div class="new_goods">
				<h3>新歌推荐</h3>
				<ul>
                    {% for songs in song_rec %}
					<li>
						<a href="/{{ songs.id }}"><img src="{{ MEDIA_URL }}{{ songs.mpic }}"></a>
						<h4><a href="#">{{ songs.mtitle }}</a></h4>
					</li>
                    {%  endfor %}
                </ul>
			</div>
		</div>

		<div class="r_wrap fr clearfix">
			<ul class="detail_tab clearfix">
				<li class="active">歌曲介绍</li>

			</ul>

			<div class="tab_content">
				<dl>
					<dt>歌曲详情：</dt>
					<dd>{{ songs.mcontext|safe }}</dd>
				</dl>
			</div>

		</div>
	</div>




{% endblock center_content %}

templates/df_music/index.html
{% extends 'base.html' %}

{% block head %}
    <script  src="/static/js/jquery-ui.min.js"></script>

	<script type="text/javascript" src="/static/js/slide.js"></script>

{% endblock head %}

{% block center_body %}

	<div class="navbar_con">
		<div class="navbar">
			<h1 class="fl">全部音乐分类</h1>
			<ul class="navlist fl">
				<li><a href="{% url "df_goods:index" %}">首页</a></li>
			</ul>
		</div>
	</div>

	<div class="center_con clearfix">
		<ul class="subnav fl">
			<li><a href="#model01" class="fruit">摇滚</a></li>
			<li><a href="#model02" class="seafood">古典</a></li>
		<li><a href="#model03" class="meet">轻音乐</a></li>
			<li><a href="#model04" class="egg">热歌</a></li>
			<li><a href="#model05" class="vegetables">DJ</a></li>
			<li><a href="#model06" class="ice">经典老歌</a></li>
		</ul>
		<div class="slide fl">
			<ul class="slide_pics">
				<li><img src="/static/images/slide.png" width="750" height="250" alt="幻灯片"></li>
				<li><img src="/static/images/slide02.png" width="750" height="250" alt="幻灯片"></li>
				<li><img src="/static/images/slide03.png" width="750" height="250" alt="幻灯片"></li>
				<li><img src="/static/images/slide04.png" width="750" height="250" alt="幻灯片"></li>
			</ul>
			<div class="prev"></div>
			<div class="next"></div>
			<ul class="points"></ul>
		</div>
		<div class="adv fl">
			<a href="#"><img src="/static/images/adv01.jpg" width="240px" height="260px"></a>

		</div>
	</div>

	<div class="list_model">
		<div class="list_title clearfix">
			<h3 class="fl" id="model01">摇滚</h3>
			<div class="subtitle fl">
				<span>|</span>
{#				<a href="#">鲜芒</a>#}
{#				<a href="#">加州提子</a>#}
{#				<a href="#">亚马逊牛油果</a>#}
                {% for m in type01 %}
                    <a href="/{{ m.id }}/">{{  m.mtitle|slice:'10' }}</a>
{#                    这里建立一个点击量前四位的商品的链接#}
{#                    模板过滤器slice, 取变量前 N 个字符，可用于中文 #}
                {%  endfor %}
			</div>
			<a href="/list1_1_1/" class="goods_more fr" id="fruit_more">查看更多 ></a>
		</div>

		<div class="goods_con clearfix">
			<div class="goods_banner fl"><img src="/static/images/banner01.jpg"></div>
			<ul class="goods_list fl">
{#				<li>#}
{#					<h4><a href="#">草莓</a></h4>#}
{#					<a href="#"><img src="/static/df_goods/goods003.jpg"></a>#}
{#					<div class="prize">¥ 30.00</div>#}
{#				</li>#}
                {% for songs in type0 %}
{#                    按照商品的最新上穿建立显示#}
                <li>
                    <h4><a href="/{{ songs.id }}/">{{ songs.mtitle }}</a></h4>
                    <a href="/{{ songs.id }}/"><img src="{{ MEDIA_URL }}{{ songs.mpic }}"></a>

                </li>
                {% endfor %}
			</ul>
		</div>
	</div>

	<div class="list_model">
		<div class="list_title clearfix">
			<h3 class="fl" id="model02">古典</h3>
			<div class="subtitle fl">
				<span>|</span>
{#				<a href="#">河虾</a>#}
{#				<a href="#">扇贝</a>				#}
                {% for m in type11 %}
                    <a href="/{{ m.id }}/">{{ m.mtitle|slice:'10' }}</a>
                {% endfor %}
			</div>
			<a href="/list2_1_1/" class="goods_more fr">查看更多 ></a>
		</div>

		<div class="goods_con clearfix">
			<div class="goods_banner fl"><img src="/static/images/banner02.jpg"></div>
			<ul class="goods_list fl">
                {% for songs in type1 %}
                <li>
                    <h4><a href="/{{ songs.id }}/">{{ songs.mtitle }}</a></h4>
                    <a href="/{{ songs.id }}/"><img src="{{ MEDIA_URL }}{{ songs.mpic }}"></a>
{#                    静态文件添加目录static前一定加"/"#}

                </li>
                {% endfor %}
			</ul>
		</div>
	</div>

	<div class="list_model">
		<div class="list_title clearfix">
			<h3 class="fl" id="model03">轻音乐</h3>
			<div class="subtitle fl">
				<span>|</span>
                {% for m in type21 %}
                    <a href="/{{ m.id }}/">{{ m.mtitle|slice:'10' }}</a>
                {% endfor %}

			</div>
			<a href="list3_1_1" class="goods_more fr">查看更多 ></a>
		</div>

		<div class="goods_con clearfix">
			<div class="goods_banner fl"><img src="/static/images/banner03.jpg"></div>
			<ul class="goods_list fl">
				{% for songs in type2 %}
                <li>
                    <h4><a href="/{{ songs.id }}/">{{ songs.mtitle }}</a></h4>
                    <a href="/{{ songs.id }}/"><img src="{{ MEDIA_URL }}{{ songs.mpic }}"></a>
{#                    静态文件添加目录static前一定加"/"#}

                </li>
                {% endfor %}
			</ul>
		</div>

	</div>

	<div class="list_model">
		<div class="list_title clearfix">
			<h3 class="fl" id="model04">热歌</h3>
			<div class="subtitle fl">
                <span>|</span>
				{% for m in type31 %}
                    <a href="/{{ m.id }}/">{{  m.mtitle|slice:'10' }}</a>
{#                    这里建立一个点击量前四位的商品的链接#}
{#                    模板过滤器slice, 取变量前 N 个字符，可用于中文 #}
                {%  endfor %}
			</div>
			<a href="list4_1_1" class="goods_more fr">查看更多 ></a>
		</div>

		<div class="goods_con clearfix">
			<div class="goods_banner fl"><img src="/static/images/banner04.jpg"></div>
			<ul class="goods_list fl">
				{% for songs in type3%}
                <li>
                    <h4><a href="/{{ songs.id }}/">{{ songs.mtitle }}</a></h4>
                    <a href="/{{ songs.id }}/"><img src="{{ MEDIA_URL }}{{ songs.mpic }}"></a>
{#                    静态文件添加目录static前一定加"/"#}

                </li>
                {% endfor %}
			</ul>
		</div>
	</div>

	<div class="list_model">
		<div class="list_title clearfix">
			<h3 class="fl" id="model05">DJ</h3>
			<div class="subtitle fl">
				<span>|</span>
				{% for g in type41 %}
                    <a href="/{{ g.id }}/">{{  g.mtitle|slice:'10' }}</a>
{#                    这里建立一个点击量前四位的商品的链接#}
{#                    模板过滤器slice, 取变量前 N 个字符，可用于中文 #}
                {%  endfor %}
			</div>
			<a href="list5_1_1" class="goods_more fr">查看更多 ></a>
		</div>

		<div class="goods_con clearfix">
			<div class="goods_banner fl"><img src="/static/images/banner05.jpg"></div>
			<ul class="goods_list fl">
				{% for songs in type4 %}
                <li>
                    <h4><a href="/{{ songs.id }}/">{{ songs.mtitle }}</a></h4>
                    <a href="/{{ songs.id }}/"><img src="{{ MEDIA_URL }}{{ songs.mpic }}"></a>
{#                    静态文件添加目录static前一定加"/"#}

                </li>
                {% endfor %}
			</ul>
		</div>
	</div>

	<div class="list_model">
		<div class="list_title clearfix">
			<h3 class="fl" id="model06">经典老歌</h3>
			<div class="subtitle fl">
				<span>|</span>
				{% for g in type51 %}
                    <a href="/{{ g.id }}/">{{  g.mtitle|slice:'10' }}</a>
{#                    这里建立一个点击量前四位的商品的链接#}
{#                    模板过滤器slice, 取变量前 N 个字符，可用于中文 #}
                {%  endfor %}
			</div>
			<a href="list6_1_1" class="goods_more fr">查看更多 ></a>
		</div>

		<div class="goods_con clearfix">
			<div class="goods_banner fl"><img src="/static/images/banner06.jpg"></div>
			<ul class="goods_list fl">
				{% for songs in type5 %}
                <li>
                    <h4><a href="/{{ songs.id }}/">{{ songs.mtitle }}</a></h4>
                    <a href="/{{ songs.id }}/"><img src="{{ MEDIA_URL }}{{ songs.mpic }}"></a>
{#                    静态文件添加目录static前一定加"/"#}

                </li>
                {% endfor %}
			</ul>
		</div>
	</div>

	<script type="text/javascript" src="/static/js/slide.js"></script>
    <script type="text/javascript">
        BCSlideshow('focuspic');
        var oFruit = document.getElementById('fruit_more');
        var oShownum = document.getElementById('show_count');

        var hasorder = localStorage.getItem('order_finish');

        if(hasorder)
        {
        oShownum.innerHTML = '2';
        }

        oFruit.onclick = function(){
        window.location.href = 'list.html';
        }
    </script>

{% endblock center_body %}

templates/df_music/list.html
{% extends 'df_music/base.html' %}

{% block center_content %}

	<div class="main_wrap clearfix">
		<div class="l_wrap fl clearfix">
			<div class="new_goods">
				<h3>新歌推荐</h3>
				<ul>



                    {% for songs in news %}
{#                        新歌推荐两种#}
                        <li>
                            <a href="/{{ songs.id }}"><img src="{{ MEDIA_URL }}{{ songs.mpic }}"></a>
    						<h4><a href="/{{ songs.id }}">{{ songs.mtitle }}</a></h4>

                        </li>
                    {% endfor %}
				</ul>
			</div>
		</div>

		<div class="r_wrap fr clearfix">
			<div class="sort_bar">

{#				<a href="#" class="active">默认</a>#}
{#				<a href="#">价格</a>#}
{#				<a href="#">人气</a>#}

{#          注意视图函数中的传参顺序 另外在url中传递的链接全为字符型  #}
                <a href="/list{{ typeinfo.id }}_1_1"
                   {% if sort == '1' %}
                    class="active"
                   {% endif %}
                    >点击量</a>
                <a href="/list{{ typeinfo.id }}_1_2"
                   {% if sort == '2' %}
                    class="active"
                   {% endif %}
                    >默认</a>

			</div>

			<ul class="goods_type_list clearfix">

{#				<li>#}
{#					<a href="detail.html"><img src="/static/images/goods/goods003.jpg"></a>#}
{#					<h4><a href="detail.html">大兴大棚草莓</a></h4>#}
{#					<div class="operate">#}
{#						<span class="prize">￥16.80</span>#}
{#						<span class="unit">16.80/500g</span>#}
{#						<a href="#" class="add_goods" title="加入购物车"></a>#}
{#					</div>#}
{#				</li>#}

                {%  for g in page %}
                <li>
					<a href="/{{ g.id }}/"><img src="{{ MEDIA_URL }}{{ g.mpic }}"></a>
					<h4><a href="/{{ g.id }}/">{{ g.gtitle }}</a></h4>

				</li>
                {% endfor %}
			</ul>

			<div class="pagenation">
{#                判断是否是第一页#}
                {% if page.has_previous %}
                    <a href="/list{{ typeinfo.id }}_{{ page.previous_page_number }}_{{ sort }}">上一页</a>
                {% endif %}

                {% for pindex in paginator.page_range %}
                    {% if pindex == page.number %}
                        <a href="/list{{ typeinfo.id }}_{{pindex}}_{{ sort }}" class="active">{{ pindex }}</a>
                    {% else %}
                        <a href="/list{{ typeinfo.id }}_{{pindex}}_{{ sort }}">{{ pindex }}</a>
                    {% endif %}
                {% endfor %}

{#                是否为第二页#}
                {% if page.has_next %}
				<a href="/list{{ typeinfo.id }}_{{ page.next_page_number }}_{{ sort }}">下一页></a>
                {% endif %}
			</div>
		</div>
	</div>

{% endblock center_content %}

templates/df_music/ordinary_search.html
{% extends 'base.html' %}

{% load staticfiles %}

{% block head %}

{% endblock %}

{% block center_body %}
    <div class="navbar_con">
		<div class="navbar clearfix">
			<div class="subnav_con fl">
				<h1>全部歌曲分类</h1>
				<span></span>
				<ul class="subnav">
					<li><a href="/list1_1_1/" class="fruit">摇滚</a></li>
					<li><a href="/list2_1_1/" class="seafood">古典</a></li>
					<li><a href="/list3_1_1/" class="meet">轻音乐</a></li>
					<li><a href="/list4_1_1/" class="egg">热歌</a></li>
					<li><a href="/list5_1_1/" class="vegetables">DJ</a></li>
					<li><a href="/list6_1_1/" class="ice">经典老歌</a></li>
				</ul>
			</div>
			<ul class="navlist fl">
				<li><a href="{% url "df_goods:index" %}">首页</a></li>
			</ul>
		</div>
	</div>
    <script type="text/javascript">
        if({{ search_status }}== 0 ){

            alert("您的查询结果为空，为您推荐以下商品");
        }
    </script>
	<div class="breadcrumb">
		全部分类
{#        {{ title }}#}
{#		{% if id|default:' ' != ' ' %}#}
        > 歌曲详情
{#		{% endif %}#}
	</div>

    <div class="main_wrap clearfix">
        <ul class="goods_type_list clearfix">
            {%  for item in page %}
            <li>
                <a href="/{{ item.id }}/"><img src="{{ MEDIA_URL }}{{ item.pic }}"></a>
                <h4><a href="/{{ item.id }}/">{{ item.mtitle }}</a></h4>
            </li>
            {% endfor %}
        </ul>
        <div class="pagenation">
{#                判断是否是第一页#}
            {% if page.has_previous %}
                <a href="{% url "df_user:ordinary_search" %}?q={{ query }}&amp;page={{ page.previous_page_number }}">上一页</a>
            {% endif %}

            {% for pindex in paginator.page_range %}
                {% if pindex == page.number %}
                    <a href="#" class="active">{{ pindex }}</a>
                {% else %}
                    <a href="{% url "df_user:ordinary_search" %}?q={{ query }}&amp;page={{ pindex }}">{{ pindex }}</a>
                {% endif %}
            {% endfor %}

{#                是否又第二页#}
            {% if page.has_next %}
                <a href="{% url "df_user:ordinary_search" %}?q={{ query }}&amp;page={{ page.next_page_number }}">下一页></a>
            {% endif %}
        </div>
    </div>
{% endblock center_body %}