apps/df_music/urls.py
from django.conf.urls import url

from . import views

app_name = 'df_goods'

urlpatterns = [
    url('^$', views.index, name="index"),
    url('^list(\d+)_(\d+)_(\d+)/$', views.song_list, name="song_list"),
    url('^(\d+)/$', views.detail, name="detail"),
    url(r'^search/', views.ordinary_search, name="ordinary_search"),  # 全文检索
]

apps/df_user/urls.py
from django.conf.urls import url

from .views import *


app_name = 'df_user'

urlpatterns = [
    url(r'^register/$', register, name="register"),
    url(r'^register_handle/$', register_handle, name="register_handle"),
    url(r'^register_exist/$', register_exist, name="register_exist"),
    url(r'^login/$', login, name="login"),
    url(r'^login_handle/$', login_handle, name="login_handle"),
    url(r'^info/$', info, name="info"),

    # url(r'^place_order/$', views.place_order),
    url(r'^logout/$', logout, name="logout"),
]

musicrec/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include
from django.views.static import serve
from .settings import MEDIA_ROOT
urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^',include('df_music.urls',namespace='df_goods')),
    url(r'^user/',include('df_user.urls',namespace='df_user')),
    url(r'^tinymce/',include('tinymce.urls')),
    url(r'^media/(?P<path>.*)$', serve, {"document_root":MEDIA_ROOT}),


]

apps/df_user/models.py
from django.db import models
from datetime import datetime
from df_music.models import MusicInfo
# Create your models here.
class UserInfo(models.Model):
    uname=models.CharField(max_length=20,verbose_name="用户名",unique=True)
    upwd=models.CharField(max_length=40,verbose_name="用户密码",blank=False)
    uage=models.IntegerField(verbose_name="年龄")
    ugender=models.CharField(max_length=1,verbose_name="性别")
    uemail=models.EmailField(verbose_name="邮箱",unique=True)
    uphone=models.CharField(max_length=11,default="",verbose_name="手机号")

    class Meta:
        verbose_name="用户信息"
        verbose_name_plural=verbose_name
    def __str__(self):
        return self.uname

class MusicBrowser(models.Model):
    user=models.ForeignKey(UserInfo,on_delete=models.CASCADE,verbose_name="用户ID")
    music=models.ForeignKey(MusicInfo,on_delete=models.CASCADE,verbose_name="歌曲ID")
    browser_time=models.DateTimeField(default=datetime.now,verbose_name="浏览时间")

    class Meta:
        verbose_name="用户浏览记录"
        verbose_name_plural=verbose_name
    def __str__(self):
        return "{0}浏览记录{1}".format(self.user.uname,self.music.mtitle)

apps/df_user/views.py
from hashlib import sha1
from django.http import JsonResponse
from django.shortcuts import render, redirect,HttpResponseRedirect,reverse
from .models import MusicBrowser,UserInfo
from django.core.paginator import Paginator
from . import user_decorator



# Create your views here.
def register(request):
    context={
        'title':'用户注册',
    }
    return render(request, 'df_user/register.html', context)
def register_handle(request):

    username=request.POST.get('user_name')
    password=request.POST.get('pwd')
    confirm_pwd=request.POST.get('confirm_pwd')
    age=request.POST.get("age")
    gender=request.POST.get("gender")
    email=request.POST.get('email')



    if password!=confirm_pwd:
        return redirect('/user/register/')
    s1=sha1()
    s1.update(password.encode('utf8'))
    encrypted_pwd=s1.hexdigest()

    UserInfo.objects.create(uname=username,upwd=encrypted_pwd,uemail=email,uage=int(age),ugender=gender)


    context={
        'title':'用户登录',
        'username':username
    }
    return render(request, 'df_user/login.html', context)
def register_exist(request):
    username=request.GET.get('uname')
    count=UserInfo.objects.filter(uname=username).count()
    return JsonResponse({'count':count})

def login(request):
    uname=request.COOKIES.get('uname','')
    context={
        'title':'用户登录',
        'error_name':0,
        'error_pwd':0,
        'uname':uname,
    }
    return render(request, 'df_user/login.html', context)

def login_handle(request):
    uname=request.POST.get('username')
    upwd=request.POST.get('pwd')
    jizhu=request.POST.get('jizhu',0)
    users=UserInfo.objects.filter(uname=uname)
    if len(users)==1:
        s1=sha1()
        s1.update(upwd.encode('utf8'))
        if s1.hexdigest()==users[0].upwd:
            url=request.COOKIES.get('url','/')
            red=HttpResponseRedirect(url)
            if jizhu!=0:
                red.set_cookie('uname',uname)
            else :
                red.set_cookie('uname','',max_age=-1)
            request.session['user_id']=users[0].id
            request.session['user_name']=uname
            return red
        else:
            context={
                'title':"用户名登陆",
                'error_name':0,
                'error_pwd':1,
                'uname':uname,
                'upwd':upwd
            }
            return render(request,'df_user/login.html',context)
    else:
        context={
            'title':'用户名登陆',
            'error_name':1,
            'error_pwd':0,
            'uname':uname,
            'upwd':upwd,
        }
        return render(request,'df_user/login.html',context)
def logout(request):
    request.session.flush()
    return redirect(reverse("df_goods:index"))

@user_decorator.login
def info(request):
    username=request.session.get('user_name')
    user=UserInfo.objects.filter(uname=username).first()
    browser_musics=MusicBrowser.objects.filter(user=user).order_by("-browser_time")
    music_list=[]
    if browser_musics:
        music_list=[browser_music.music for browser_music in browser_musics ]
        explain='最近浏览'
    else:
        explain='无最近浏览'
    context={
        'title':'用户中心',
        'page_name':1,
        'user_name':username,
        'music_list':music_list,
        'explain':explain,
    }
    return render(request,'df_user/user_center_info.html',context)

templates/df_user/login.html
{% extends 'base_foot.html' %}

{% block head %}

    <script src="/static/js/jquery-1.12.4.min.js">
    $(function () {
        name_error = false;
        pwd_error = false;

        if({{ error_name }}==1){
            $('.user_error').html('用户名错误').show();
        }
        if({{ error_pwd }}==1){
            $('.pwd_error').html('密码错误').show();
        }
        $('.name_input').blur(function () {
            if($('.name_input').val().length=0){
                $('.user_error').html('请填写用户名').show();
                name_error = false;
            }else{
                $('.user_error').hide();
                name_error = true;
            }
        });
        $('.pass_input').blur(function () {
            if($('.pass_input').val().length=0){
                $('.pwd_error').html('请输入密码').show();
                pwd_error = false;

            }else{
                $('.pwd_error').hide();
                pwd_error = true;
            }
        })
    })
</script>
{% endblock head %}

{% block body %}
	<div class="login_top clearfix">
		<a href="{% url "df_goods:index" %}" class="login_logo"><img src="/static/images/logo02.png" style="margin-top: 150px"></a>
	</div>

	<div class="login_form_bg">
		<div class="login_form_wrap clearfix">
			<div class="login_banner fl"></div>
			<div class="login_form fr">
				<div class="login_title clearfix">
					<h1>用户登录</h1>
					<a href="{% url "df_user:register" %}">立即注册</a>
				</div>
				<div class="form_input">
					<form action="{% url "df_user:login_handle" %}" method="post">
                        {% csrf_token %}
						<input type="text" name="username" class="name_input" value="{{ username }}" placeholder="请输入用户名">
						<div class="user_error">输入错误</div>
						<input type="password" name="pwd" class="pass_input" value="{{ password }}" placeholder="请输入密码">
{#                        在cookie设置的情况下value值保证页面刷新之后保证仍旧能够在页面看到值#}
						<div class="pwd_error">输入错误</div>
						<div class="more_input clearfix">
							<input type="checkbox" name="jizhu" value="1" checked="checked">
							<label>记住用户名</label>
							<a href="#">忘记密码</a>
						</div>
						<input type="submit" name="" value="登录" class="input_submit">
					</form>
				</div>
			</div>
		</div>
	</div>

{% endblock body %}

templates/df_user/register.html
{% extends 'base_foot.html' %}
{#模板继承于base_foot#}

{% block head %}
    <script type="text/javascript" src="/static/js/register.js"></script>
    <script src="/static/js/jquery-1.12.4.min.js"></script>
    <script type="text/javascript">
    $(function(){

	var error_name = false;
	var error_password = false;
	var error_check_password = false;
	var error_email = false;
	var error_age=false;
	var error_gender=false;
	var error_check = false;



	$('#user_name').blur(function() {
		check_user_name();
	});

	$('#pwd').blur(function() {
		check_pwd();
	});

	$('#cpwd').blur(function() {
		check_cpwd();
	});

	$('#email').blur(function() {
		check_email();
	});



	$('#allow').click(function() {
		if($(this).is(':checked'))
		{
			error_check = false;
			$(this).siblings('span').hide();
		}
		else
		{
			error_check = true;
			$(this).siblings('span').html('请勾选同意');
			$(this).siblings('span').show();
		}
	});


	function check_user_name(){
		var len = $('#user_name').val().length;

		if(len<5||len>20)
		{
			$('#user_name').next().html('输入5-20个字符的用户名');
			$('#user_name').next().show();
			error_name = true;

		}
		else
		{
			$.get('{% url "df_user:register_exist" %}?uname='+$('#user_name').val(),function(data){
                if (data.count >= 1) {
                    $('#user_name').next().html('用户名已经存在').show();
                    error_name = true;
                }else{
                    $('#user_name').next().hide();
                    error_name = false;
                }
            });
        }
	}

	function check_pwd(){
		var len = $('#pwd').val().length;
		if(len<4||len>20)
		{
			$('#pwd').next().html('密码最少4位，最长20位');
			$('#pwd').next().show();
			error_password = true;
		}
		else
		{
			$('#pwd').next().hide();
			error_password = false;
		}
	}


	function check_cpwd(){
		var pass = $('#pwd').val();
		var cpass = $('#cpwd').val();

		if(pass!=cpass)
		{
			$('#cpwd').next().html('两次输入的密码不一致');
			$('#cpwd').next().show();
			error_check_password = true;
		}
		else
		{
			$('#cpwd').next().hide();
			error_check_password = false;
		}

	}

	function check_email(){
		var re = /^[a-z0-9][\w\.\-]*@[a-z0-9\-]+(\.[a-z]{2,5}){1,2}$/;

		if(re.test($('#email').val()))
		{
			$('#email').next().hide();
			error_email = false;
		}
		else
		{
			$('#email').next().html('你输入的邮箱格式不正确');
			$('#email').next().show();
			error_check_password = true;
		}

	}



	$('#reg_form').submit(function() {
		check_user_name();
		check_pwd();
		check_cpwd();
		check_email();

		if(error_name == false && error_password == false && error_check_password == false && error_email == false && error_check == false)
		{
			return true;
		}
		else
		{
			return false;
		}

	});
});
    </script>
{% endblock head %}

{% block body %}
	<div class="register_con">
		<div class="l_con fl">
			<a class="reg_logo" style="margin-left:-60px"><img src="/static/images/logo02.png"></a>
			<div class="reg_slogan">轻奢音乐  ·  快乐每一天</div>
			<div class="reg_banner"></div>
		</div>

		<div class="r_con fr">
			<div class="reg_title clearfix">
				<h1>用户注册</h1>
				<a href="{% url "df_user:login" %}">登录</a>
			</div>
			<div class="reg_form clearfix">
				<form action="{% url "df_user:register_handle" %}" id='reg_form' method="post">
                    {% csrf_token %}
				<ul>
					<li>
						<label>用户名:</label>
						<input type="text" name="user_name" id="user_name">
						<span class="error_tip">提示信息</span>
					</li>
					<li>
						<label>密码:</label>
						<input type="password" name="pwd" id="pwd">
						<span class="error_tip">提示信息</span>
					</li>
					<li>
						<label>确认密码:</label>
						<input type="password" name="confirm_pwd" id="cpwd">
						<span class="error_tip">提示信息</span>
					</li>
                    <li>
						<label>年龄:</label>
						<input type="text" name="age" id="age">
					</li>
                    <li>
						<label>性别:</label>
						<input type="text" name="gender" id="gender">
					</li>
					<li>
						<label>邮箱:</label>
						<input type="text" name="email" id="email">
						<span class="error_tip">提示信息</span>
					</li>
					<li class="agreement">
						<input type="checkbox" name="allow" id="allow" checked="checked">
						<label>同意《每日音乐用户使用协议》</label>
						<span class="error_tip2">提示信息</span>
					</li>
					<li class="reg_sub">
						<input type="submit" value="注 册">
					</li>
				</ul>
				</form>
			</div>

		</div>

	</div>

{% endblock body %}

templates/df_user/user_center_info.html
{% extends 'base.html' %}

{% block center_body %}


	<div class="main_con clearfix">
		<div class="left_menu_con clearfix">
			<h3>用户中心</h3>
			<ul>
				<li><a href="{% url "df_user:info" %}" class="active">· 个人信息</a></li>

			</ul>
		</div>
		<div class="right_content clearfix">
				<div class="info_con clearfix">
				<h3 class="common_title2">基本信息</h3>
						<ul class="user_info_list">
							<li><span>用户名：</span>{{ user_name }}</li>

						</ul>
				</div>
            <h3 class="common_title2">{{ explain }}</h3>
            <div class="has_view_list">
                <ul class="goods_type_list clearfix">
                    {%  for music in music_list %}
                    <li>
                        <a href="/{{ music.id }}/"><img src="{{ MEDIA_URL }}{{ music.mpic }}"></a>
                        <h4><a href="/{{ music.id }}/">{{ music.mtitle }}</a></h4>

                    </li>
                    {% endfor %}
			</ul>
            </div>
		</div>
	</div>
{% endblock center_body %}