apps/df_music/urls.py
from django.conf.urls import url

from . import views

app_name = 'df_goods'

urlpatterns = [
    url('^$', views.index, name="index"),
    url('^list(\d+)_(\d+)_(\d+)/$', views.song_list, name="song_list"),
    url('^(\d+)/$', views.detail, name="detail"),
    url(r'^search/', views.ordinary_search, name="ordinary_search"),  # 全文检索
]

apps/df_user/urls.py
from django.conf.urls import url

from .views import *


app_name = 'df_user'

urlpatterns = [
    url(r'^register/$', register, name="register"),
    url(r'^register_handle/$', register_handle, name="register_handle"),
    url(r'^register_exist/$', register_exist, name="register_exist"),
    url(r'^login/$', login, name="login"),
    url(r'^login_handle/$', login_handle, name="login_handle"),
    url(r'^info/$', info, name="info"),

    # url(r'^place_order/$', views.place_order),
    url(r'^logout/$', logout, name="logout"),
]

musicrec/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include
from django.views.static import serve
from .settings import MEDIA_ROOT
urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^',include('df_music.urls',namespace='df_goods')),
    url(r'^user/',include('df_user.urls',namespace='df_user')),
    url(r'^tinymce/',include('tinymce.urls')),
    url(r'^media/(?P<path>.*)$', serve, {"document_root":MEDIA_ROOT}),


]

templates/base.html
{% extends 'base_foot.html' %}
{% block body %}

    <div class="header_con">
		<div class="header">
			<div class="welcome fl">欢迎来到每日音乐!</div>
			<div class="fr">
{#                判断是否已经登录#}
                {% if request.session.user_name|default:'' != '' %}
{#                    default过滤器进行判断如果request.session.user_name不等于空字符串则用户登陆状态为true#}
{#                    也就是说当用户为已登陆状态时则显示用户名#}

{#                    class="login_info fl"#}
				<div class="login_btn fl">欢迎您：<em>{{ request.session.user_name }}</em>
                    <span>|</span>
                    <em><a href="{% url "df_user:logout" %}">退出</a></em>
				</div>
                {% else %}
				<div class="login_btn fl">
					<a href="{% url "df_user:login" %}">登录</a>
					<span>|</span>
					<a href="{% url "df_user:register" %}">注册</a>
				</div>
                {% endif %}
				<div class="user_link fl">
					<span>|</span>
					<a href="{% url "df_user:info" %}">用户中心</a>
					<span>|</span>

				</div>
			</div>
		</div>
	</div>


    <div class="search_bar clearfix">
		<a href="/" class="logo fl" ><img src="/static/images/logo.png" width="200px" height="80px" ></a>
        {% if page_name == 1 %}
            <div class="sub_page_name fl">|&nbsp;&nbsp;&nbsp;&nbsp;{{ title }}</div>
        {% endif %}
		<div class="search_con fl">
           <script src="/static/js/jquery-1.12.4.min.js"></script>
            <script>

$(function () {
                    $('.input_btn').click(function () {
                        q = $('.input_text').val();
                        if(q==""){
                        alert("请输入搜索内容");
                        }
                        else{
                            location.href = '{% url "df_goods:ordinary_search" %}?q='+q+'&page=1'
                        }
                    })
                })
            </script>
			<input type="text" class="input_text fl" name="q" placeholder="搜索音乐">
			<input type="button" class="input_btn fr" name="" value="搜索">
		</div>
	</div>




{% block content %}
{% endblock content %}
{% block center_body %}

{% endblock center_body %}


{% endblock body %}

templates/base_foot.html
<!DOCTYPE html>
<html lang="en">
{% load staticfiles %}
<head>
    <meta charset="UTF-8">
    <title>{{ title }}|每日音乐</title>
    <link rel="stylesheet" type="text/css" href="/static/css/main.css">
    <link rel="stylesheet" type="text/css" href="/static/css/reset.css">
    <script type="text/javascript" scr="/static/js/jquery-1.12.4.min.js"></script>>
    {% block head %}{% endblock head %}

</head>
<body>
{% block body %}{% endblock body %}
<div class="footer no-mp">
		<div class="foot_link">
			<a href="#">关于我们</a>
			<span>|</span>
			<a href="#">联系我们</a>
			<span>|</span>
			<a href="#">招聘人才</a>
			<span>|</span>
			<a href="#">友情链接</a>
		</div>
		<p> All Rights Reserved</p>
		<p>电话：***-*******    京ICP备********号</p>
	</div>

</body>
</html>